// open the demograph file generated by BacStalk (check "show full cell width" setting)

run("8-bit");
setAutoThreshold("Default dark");
run("Threshold...");
setThreshold(1, 255);
setOption("BlackBackground", false);
run("Close");
run("Convert to Mask");
run("Analyze Particles...", "exclude clear add");

// save ROIs to file